[FIR] Mute `LLReversedNativeDiagnosticsTestGenerated.testIdentifiers`
It now fails for the same reason as the non-reversed runner.

^KT-62937

The source of the issue is that the name `Class.Class` is sometimes
passed to `FqName()` without the proper escaping with backticks. Turns
out it's a big problem that needs to be addressed separately: KT-87228.

```
ERROR: The diagnostic collector has been interrupted by an exception. The result may be incomplete

Attachments:
info.txt
- classifierClassId:
    Class: org.jetbrains.kotlin.name.ClassId
Value:
    totally/normal/pkg/Check.Class

========
- classifier:
    Class: org.jetbrains.kotlin.psi.KtClass
Value:
    <File name: 2.kt, Physical: true>
<ELEMENT>class `Check.Class`</ELEMENT>

========
- classifierModule:
    Class: org.jetbrains.kotlin.analysis.test.framework.projectStructure.KaSourceModuleByCompilerConfiguration
Value:
    Sources of main

========
- virtualFile:
    Class: com.intellij.testFramework.LightVirtualFile
Value:
    path: /2.kt, filetype: org.jetbrains.kotlin.idea.KotlinFileType@3071401c ,filesystem,com.intellij.testFramework.LightVirtualFileBase$MyVirtualFileSystem@3e7ce9f5

========

org.jetbrains.kotlin.utils.exceptions.KotlinIllegalArgumentExceptionWithAttachments: Classifier was found in KtFile but was not found in FirFile
	at org.jetbrains.kotlin.analysis.low.level.api.fir.symbolProviders.LLKotlinSourceSymbolProvider.computeClassLikeSymbolByClassId(LLKotlinSourceSymbolProvider.kt:387)
	at org.jetbrains.kotlin.analysis.low.level.api.fir.symbolProviders.LLKotlinSourceSymbolProvider.access$computeClassLikeSymbolByClassId(LLKotlinSourceSymbolProvider.kt:72)
	at org.jetbrains.kotlin.analysis.low.level.api.fir.symbolProviders.LLKotlinSourceSymbolProvider$classLikeCache$1.invoke(LLKotlinSourceSymbolProvider.kt:116)
	at org.jetbrains.kotlin.analysis.low.level.api.fir.symbolProviders.LLKotlinSourceSymbolProvider$classLikeCache$1.invoke(LLKotlinSourceSymbolProvider.kt:116)
```